<!-- header start -->
<div class="header">
    <div class="wrapper clearfix">
        <a href="${baseUrl}" class="logo clearfix">
            <div class="logo-wrap">
                <img src="../img/logo.png"/>
            </div>
            <div class="title-wrap">
            	<h1 class="title">${siteTitle}</h1>
        		<p class="sub-title">${siteEnglishTitle}</p>
            </div>
        </a>
        <div class="tool-bar">
        	<div class="qrcode">
        		<img src="../img/qrcode.png"/>
        	</div>
        </div>

    </div>
</div>
<!-- header end -->
<!-- nav start -->
<div class="nav">
	<div class="wrapper">
		<ul class="clearfix">
			<!-- loop -->
			<li>
				<a href="#">nav 1</a>
			</li>
			<!-- loop end -->
		</ul>
	</div>
</div>
<!-- nav end -->