<!-- simple footer start -->
<div class="simple-footer">
    <div class="wrapper">
        <p class="links">
            <span>
                <a href="#">xxx</a>
            </span>
            <span>
                <a href="#">xxx</a>
            </span>
            <span>
                <a href="#">xxx</a>
            </span>
            <span>
                <a href="#">xxx</a>
            </span>
            <span>
                <a href="#">xxx</a>
            </span>
            <span>
                <a href="#">xxx</a>
            </span>
            <span>
                <a href="#">xxx</a>
            </span>
        </p>
        <p class="copyrights">${copyRights}</p>
    </div>
</div>
<!-- simple footer end -->